### ISSUE TITLE
data source

### ISSUE THREAD

**Issue by jakobzhao** [zochg/CenturyFarmsOR#3]
Have you tested whether all the data sources are downloadable?

**Comment by jakobzhao** [comment]
Please try to respond to the issue I suggested.

**Comment by zochg** [comment]
Bo! I'm sorry I just noticed that there was this issues tab available on the repository... I've fixed the name issue and the images folder issue. I have the data downloaded already as well so no problem there. I'm really sorry it took my 14 days to resolve this!
